/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as DlqRouteImport } from './routes/dlq'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JobsIndexRouteImport } from './routes/jobs/index'
import { Route as ConsumersIndexRouteImport } from './routes/consumers/index'
import { Route as JobsJobIdRouteImport } from './routes/jobs/$jobId'
import { Route as ConsumersCreateRouteImport } from './routes/consumers/create'
import { Route as ConsumersConsumerIdRouteImport } from './routes/consumers/$consumerId'

const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const DlqRoute = DlqRouteImport.update({
  id: '/dlq',
  path: '/dlq',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsIndexRoute = JobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsumersIndexRoute = ConsumersIndexRouteImport.update({
  id: '/consumers/',
  path: '/consumers/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsJobIdRoute = JobsJobIdRouteImport.update({
  id: '/jobs/$jobId',
  path: '/jobs/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsumersCreateRoute = ConsumersCreateRouteImport.update({
  id: '/consumers/create',
  path: '/consumers/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsumersConsumerIdRoute = ConsumersConsumerIdRouteImport.update({
  id: '/consumers/$consumerId',
  path: '/consumers/$consumerId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dlq': typeof DlqRoute
  '/stats': typeof StatsRoute
  '/consumers/$consumerId': typeof ConsumersConsumerIdRoute
  '/consumers/create': typeof ConsumersCreateRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/consumers/': typeof ConsumersIndexRoute
  '/jobs/': typeof JobsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dlq': typeof DlqRoute
  '/stats': typeof StatsRoute
  '/consumers/$consumerId': typeof ConsumersConsumerIdRoute
  '/consumers/create': typeof ConsumersCreateRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/consumers': typeof ConsumersIndexRoute
  '/jobs': typeof JobsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dlq': typeof DlqRoute
  '/stats': typeof StatsRoute
  '/consumers/$consumerId': typeof ConsumersConsumerIdRoute
  '/consumers/create': typeof ConsumersCreateRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/consumers/': typeof ConsumersIndexRoute
  '/jobs/': typeof JobsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dlq'
    | '/stats'
    | '/consumers/$consumerId'
    | '/consumers/create'
    | '/jobs/$jobId'
    | '/consumers/'
    | '/jobs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dlq'
    | '/stats'
    | '/consumers/$consumerId'
    | '/consumers/create'
    | '/jobs/$jobId'
    | '/consumers'
    | '/jobs'
  id:
    | '__root__'
    | '/'
    | '/dlq'
    | '/stats'
    | '/consumers/$consumerId'
    | '/consumers/create'
    | '/jobs/$jobId'
    | '/consumers/'
    | '/jobs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DlqRoute: typeof DlqRoute
  StatsRoute: typeof StatsRoute
  ConsumersConsumerIdRoute: typeof ConsumersConsumerIdRoute
  ConsumersCreateRoute: typeof ConsumersCreateRoute
  JobsJobIdRoute: typeof JobsJobIdRoute
  ConsumersIndexRoute: typeof ConsumersIndexRoute
  JobsIndexRoute: typeof JobsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dlq': {
      id: '/dlq'
      path: '/dlq'
      fullPath: '/dlq'
      preLoaderRoute: typeof DlqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/': {
      id: '/jobs/'
      path: '/jobs'
      fullPath: '/jobs/'
      preLoaderRoute: typeof JobsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consumers/': {
      id: '/consumers/'
      path: '/consumers'
      fullPath: '/consumers/'
      preLoaderRoute: typeof ConsumersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$jobId': {
      id: '/jobs/$jobId'
      path: '/jobs/$jobId'
      fullPath: '/jobs/$jobId'
      preLoaderRoute: typeof JobsJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consumers/create': {
      id: '/consumers/create'
      path: '/consumers/create'
      fullPath: '/consumers/create'
      preLoaderRoute: typeof ConsumersCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consumers/$consumerId': {
      id: '/consumers/$consumerId'
      path: '/consumers/$consumerId'
      fullPath: '/consumers/$consumerId'
      preLoaderRoute: typeof ConsumersConsumerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DlqRoute: DlqRoute,
  StatsRoute: StatsRoute,
  ConsumersConsumerIdRoute: ConsumersConsumerIdRoute,
  ConsumersCreateRoute: ConsumersCreateRoute,
  JobsJobIdRoute: JobsJobIdRoute,
  ConsumersIndexRoute: ConsumersIndexRoute,
  JobsIndexRoute: JobsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
